# Treiber-Stack Kotlin Multiplatform Dependencies

[versions]
kotlin = "2.2.0"
coroutines = "1.9.0"
atomicfu = "0.30.0-beta"
dokka = "1.9.20"
central-portal = "1.2.3"

[libraries]
# Kotlin Multiplatform
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "maven-publish" }
signing = { id = "signing" }
central-portal = { id = "com.gradle.plugin-publish", version.ref = "central-portal" }
